---
title: "Lab 07 - University of Edinburgh Art Collection"
author: "Zheqi"
date: "2/23"
output: github_document
---

### Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse) 
library(skimr)
library(rvest)
# set url
first_url <- "https://collections.ed.ac.uk/art/search/*:*/Collection:%22edinburgh+college+of+art%7C%7C%7CEdinburgh+College+of+Art%22?offset=0"

# read html page
page <- read_html(first_url)
```

```{r load-data, message = FALSE, eval = FALSE}
page %>%
  html_nodes(".iteminfo") %>%
  html_node("h3 a") %>%
  html_text()
page %>%
  html_nodes(".iteminfo") %>%
  html_node("h3 a") %>%
  html_text() %>%
  str_squish()
titles <- page %>%
  html_nodes(".iteminfo") %>%
  html_node("h3 a") %>%
  html_text() %>%
  str_squish()
page %>%
  html_nodes(".iteminfo") %>%   # same nodes
  html_node("h3 a") %>%         # as before
  html_attr("href")             # but get href attribute instead of text
```
```{r 1}
links <- page %>%
  html_nodes(".iteminfo") %>%   # same nodes
  html_node("h3 a") %>%
  html_attr("href") %>%
  str_replace(".record", "https://collections.ed.ac.uk/art/record")

```
```{r 2}
artists <- page %>%
  html_nodes(".artist") %>%
  html_text() %>%
  str_squish()
```

```{r 3}
titles <- page %>%
  html_nodes(".iteminfo") %>%
  html_node("h3 a") %>%
  html_text() %>%
  str_squish()
art_first_page <- tibble(
  title = titles, 
  link = links, 
  artist = artists
  )

art_first_page
```
```{r 4}
second_url <- "https://collections.ed.ac.uk/art/search/*:*/Collection:%22edinburgh+college+of+art%7C%7C%7CEdinburgh+College+of+Art%22?offset=10"

page <- read_html(second_url)

# scrape titles ----------------------------------------------------------------

titles <- page %>%
  html_nodes(".iteminfo") %>%
  html_node("h3 a") %>%
  html_text() %>%
  str_squish()

# scrape links -----------------------------------------------------------------

links <- page %>%
  html_nodes(".iteminfo") %>%
  html_node("h3 a") %>%
  html_attr("href") %>%
  str_replace("\\.", "___")

# scrape artists ---------------------------------------------------------------

artists <- page %>%
  html_nodes(".artist") %>%
  html_text() %>%
  str_squish()

# put together in a data frame -------------------------------------------------

second_ten <- tibble(
  title = titles,
  artist = artists,
  link = links
)
```


```{r 5}
function(url){
  
  # read page
  page <- read_html(urls)
  
  # scrape titles ----------------------------------------------------------------
  
  titles <- page %>%
    html_nodes(".iteminfo") %>%
    html_node("h3 a") %>%
    html_text() %>%
    str_squish()
  
  # scrape links -----------------------------------------------------------------
  
  links <- page %>%
    html_nodes(".iteminfo") %>%
    html_node("h3 a") %>%
    html_attr("href") %>%
    str_replace("\\.", "https://collections.ed.ac.uk/art")
  
  # scrape artists ---------------------------------------------------------------
  
  artists <- page %>%
    html_node(".artist") %>%
    html_text() %>%
    str_squish()
  
  # put together in a data frame -------------------------------------------------
  
  art_first_page <- tibble(
    title = titles,
    artist = artists,
    link = links
  )

  
}
```

```{r 6}

#same results.
```


```{r 7}


root <- "https://collections.ed.ac.uk/art/search/*:*/Collection:%22edinburgh+college+of+art%7C%7C%7CEdinburgh+College+of+Art%22?offset="

                        
```

### Exercise 9

```{r separate-title-date, error = TRUE}
uoe_art <- uoe_art %>%
  separate(title, into = c("title", "date"), sep = "\\(") %>%
  mutate(year = str_remove(date, "\\)") %>% as.numeric()) %>%
  select(title, artist, year)
```

### Exercise 10

Remove this text, and add your answer for Exercise 10 here.
Add code chunks as needed.
Don't forget to label your code chunk.
Do not use spaces in code chunk labels.

### Exercise 11

...

Add exercise headings as needed.
